[
  {
    "cmd": [],
    "name": "RECIPE CRASH (Uncaught exception)",
    "~followup_annotations": [
      "@@@STEP_EXCEPTION@@@",
      "The recipe has crashed at point 'Uncaught exception'!",
      "",
      "Traceback (most recent call last):",
      "  File \"RECIPE_REPO[recipe_engine]/recipe_engine/internal/engine.py\", in run_steps",
      "    raw_result = recipe_obj.run_steps(api, engine)",
      "  File \"RECIPE_REPO[recipe_engine]/recipe_engine/internal/recipe_deps.py\", in run_steps",
      "    properties_def, api=api)",
      "  File \"RECIPE_REPO[recipe_engine]/recipe_engine/internal/property_invoker.py\", in invoke_with_properties",
      "    arg_names, **additional_args)",
      "  File \"RECIPE_REPO[recipe_engine]/recipe_engine/internal/property_invoker.py\", in _invoke_with_properties",
      "    return callable_obj(*props, **additional_args)",
      "  File \"RECIPE_REPO[skia]/infra/bots/recipe_modules/build/examples/full.py\", line 22, in RunSteps",
      "    api.build(checkout_root=checkout_root, out_dir=out_dir)",
      "  File \"RECIPE_REPO[recipe_engine]/recipe_engine/recipe_api.py\", in _inner",
      "    return func(*a, **kw)",
      "  File \"RECIPE_REPO[skia]/infra/bots/recipe_modules/build/api.py\", line 61, in __call__",
      "    self.compile_fn(self.m, checkout_root, out_dir)",
      "  File \"RECIPE_REPO[skia]/infra/bots/recipe_modules/build/docker.py\", line 78, in compile_fn",
      "    raise Exception('Not implemented: ' + api.vars.builder_name)",
      "Exception: Not implemented: Build-Unix-GCC-x86_64-Release-Docker"
    ]
  },
  {
    "failure": {
      "humanReason": "Uncaught Exception: Exception('Not implemented: Build-Unix-GCC-x86_64-Release-Docker',)"
    },
    "name": "$result"
  }
]